# fly.toml app configuration file generated for morning-surf-2783 on 2023-04-29T22:58:26+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "morning-surf-2783"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  AWS_REGION = "auto"
  AWS_S3_PUBLIC_BASE_URL = "https://holssi-r2.jedeop.dev"
  FLY_BUILD_APP_NAME = "holssi-builds"
  FRONTEND_ORIGIN = "https://holssi.jedeop.dev"
  SELF_BASE_URL = "http://morning-surf-2783.internal:9000"
  FLY_API_HOSTNAME = "_api.internal:4280"

[[services]]
  protocol = "tcp"
  internal_port = 9000
  processes = ["app"]
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
