# fly.toml file generated for morning-surf-2783 on 2023-03-01T22:26:29+09:00

app = "morning-surf-2783"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
FRONTEND_ORIGIN = "https://holssi.jedeop.dev"
AWS_REGION = "auto"
FLY_BUILD_APP_NAME = "holssi-builds"
AWS_S3_PUBLIC_BASE_URL = "https://holssi-r2.jedeop.dev"
SELF_BASE_URL = "http://morning-surf-2783.internal:9000"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 9000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
